// <auto-generated />
using System;
using FlightControlDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightControlDB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230404104559_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightControlDB.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeparture")
                        .HasColumnType("bit");

                    b.Property<int>("PilotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PilotId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightControlDB.Models.Leg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentLeg")
                        .HasColumnType("int");

                    b.Property<bool>("IsChangeStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("bit");

                    b.Property<int>("NextLegs")
                        .HasColumnType("int");

                    b.Property<int>("WaitTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Legs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentLeg = 1,
                            IsChangeStatus = false,
                            IsEmpty = true,
                            NextLegs = 2,
                            WaitTime = 3
                        },
                        new
                        {
                            Id = 2,
                            CurrentLeg = 2,
                            IsChangeStatus = false,
                            IsEmpty = true,
                            NextLegs = 4,
                            WaitTime = 5
                        },
                        new
                        {
                            Id = 3,
                            CurrentLeg = 4,
                            IsChangeStatus = false,
                            IsEmpty = true,
                            NextLegs = 8,
                            WaitTime = 6
                        },
                        new
                        {
                            Id = 4,
                            CurrentLeg = 8,
                            IsChangeStatus = false,
                            IsEmpty = true,
                            NextLegs = 272,
                            WaitTime = 8
                        },
                        new
                        {
                            Id = 5,
                            CurrentLeg = 16,
                            IsChangeStatus = false,
                            IsEmpty = true,
                            NextLegs = 96,
                            WaitTime = 4
                        },
                        new
                        {
                            Id = 6,
                            CurrentLeg = 32,
                            IsChangeStatus = true,
                            IsEmpty = true,
                            NextLegs = 128,
                            WaitTime = 7
                        },
                        new
                        {
                            Id = 7,
                            CurrentLeg = 64,
                            IsChangeStatus = true,
                            IsEmpty = true,
                            NextLegs = 128,
                            WaitTime = 8
                        },
                        new
                        {
                            Id = 8,
                            CurrentLeg = 128,
                            IsChangeStatus = true,
                            IsEmpty = true,
                            NextLegs = 8,
                            WaitTime = 2
                        });
                });

            modelBuilder.Entity("FlightControlDB.Models.Logger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<DateTime>("In")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Out")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("LegId");

                    b.ToTable("Loggers");
                });

            modelBuilder.Entity("FlightControlDB.Models.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pilot");
                });

            modelBuilder.Entity("FlightControlDB.Models.Flight", b =>
                {
                    b.HasOne("FlightControlDB.Models.Pilot", "Pilot")
                        .WithMany()
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("FlightControlDB.Models.Logger", b =>
                {
                    b.HasOne("FlightControlDB.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightControlDB.Models.Leg", "Leg")
                        .WithMany()
                        .HasForeignKey("LegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Leg");
                });
#pragma warning restore 612, 618
        }
    }
}
